### ISSUE TITLE
[5] Create lo-fi prototypes/wireframes based for the initial requirements

### ISSUE THREAD

**Issue by pangyurui** [Alan2201038/INF2001-P5-7#6]
Description: Create lo-fi prototypes based on the 11 initial requirements before the client meeting. This is to be able to show the client a rough visualization of how we interpret the function to be and make changes accordingly. 

Goals: Create Prototypes for each of the Initial Requirement.

Success or Completion Criteria: All checkboxes checked under Sub-Issues.

Allocated Time: 4days

Start Date: 31/08/23
End Date: 06/09/23

**Comment by xoXen** [comment]
Prototype for initial requirements 2, 3 & 6 done.

2. The manager should be able to visualize the staff workload immediately on the landing page
3. The manager should be able to allocate jobs to staff for one week at a time
6. On the manager’s landing page, the top three staff with the lowest workload should be shown, and highlight all staff over 40 hours of jobs allocated

**Comment by xoXen** [comment]
Prototype for initial requirements 4 done.
Updated prototype requirements of 2, 3 & 6.

**Comment by nadhirah5** [comment]
Prototype for initial requirements 7, 8 & 10 done.

- Staff should be able to view their weekly job assignments and overall workload for the month
on their landing page
- Staff can add and edit their availability up to 5 weeks ahead of time.
- Staff can reject jobs assigned to them, but they will be warned to discuss the jobs with their
manager before proceeding with the rejection

**Comment by Alan2201038** [comment]
Prototype for initial requirements 5 done.
 - When displaying the staff availability, the workload assigned, staff’s job preference, staff’s
location at a particular date, and availabilities for the week should be shown.

**Comment by pangyurui** [comment]
Completed prototypes for initial requirements 9 & 11.

- Staff can indicate their job preference for the week
- The company’s IT administrators will oversee adding new staff and managers to the system

**Comment by alanwml** [comment]
**Sub-Issues Checklist**
- [x] [Initial Requirement 2](https://github.com/users/Alan2201038/projects/1/views/1?pane=issue&itemId=37768288)
- [x] [Initial Requirement 3](https://github.com/users/Alan2201038/projects/1/views/1?pane=issue&itemId=37768315)
- [x] [Initial Requirement 4](https://github.com/users/Alan2201038/projects/1/views/1?pane=issue&itemId=37768326)
- [x] [Initial Requirement 5](https://github.com/users/Alan2201038/projects/1/views/1?pane=issue&itemId=37767099)
- [x] [Initial Requirement 6](https://github.com/users/Alan2201038/projects/1/views/1?pane=issue&itemId=37768336)
- [x] [Initial Requirement 7](https://github.com/users/Alan2201038/projects/1/views/1?pane=issue&itemId=37768341)
- [x] [Initial Requirement 8](https://github.com/users/Alan2201038/projects/1/views/1?pane=issue&itemId=37768343)
- [x] [Initial Requirement 9](https://github.com/users/Alan2201038/projects/1/views/1?pane=issue&itemId=37768349)
- [x] [Initial Requirement 10](https://github.com/users/Alan2201038/projects/1/views/1?pane=issue&itemId=37768354)
- [x] [Initial Requirement 11](https://github.com/users/Alan2201038/projects/1/views/1?pane=issue&itemId=37768359)
